version: "2.1"
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - run: "hello hello"
      - run: "my name is Jon"
workflows:
  test_my_app:
    jobs:
      - test
